// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPeerCount():Promise<number>;

export function GetUsername():Promise<string>;

export function GetWiFiName():Promise<string>;

export function SendMessage(arg1:string):Promise<void>;

export function SetUsername(arg1:string):Promise<void>;
