// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPeerCount() {
  return window['go']['main']['App']['GetPeerCount']();
}

export function GetUsername() {
  return window['go']['main']['App']['GetUsername']();
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetUsername(arg1) {
  return window['go']['main']['App']['SetUsername'](arg1);
}
